version: '3'
services:

  app:
    container_name: backend_apiLogin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
