version: '3'
services:

  db:
    container_name: mariaDB_apiLogin
    image: mariadb:jammy
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  app:
    container_name: backend_apiLogin
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G


volumes:
  mariadb:
    external: true
